---
- name: Install and Configure Monitoring Stack
  hosts: control
  become: yes
  vars:
    prometheus_version: "2.53.3"
    alertmanager_version: "0.28.0"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Create Prometheus system user
      user:
        name: prometheus
        shell: /bin/false
        system: yes
        create_home: no

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Prometheus files
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: prometheus
        group: prometheus
        mode: '0755'
        remote_src: yes
      loop:
        - { src: 'prometheus', dest: '/usr/local/bin/prometheus' }
        - { src: 'promtool', dest: '/usr/local/bin/promtool' }

    - name: Copy Prometheus support files
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/"
        owner: prometheus
        group: prometheus
        remote_src: yes
      loop:
        - consoles
        - console_libraries

    - name: Copy Prometheus config
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        remote_src: yes

    - name: Configure Prometheus service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        daemon_reload: yes
        state: started
        enabled: yes

    - name: Create Alertmanager directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      loop:
        - /etc/alertmanager
        - /var/lib/alertmanager

    - name: Download Alertmanager
      get_url:
        url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
        dest: /tmp/alertmanager.tar.gz

    - name: Extract Alertmanager
      unarchive:
        src: /tmp/alertmanager.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Alertmanager files
      copy:
        src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: prometheus
        group: prometheus
        mode: '0755'
        remote_src: yes
      loop:
        - { src: 'alertmanager', dest: '/usr/local/bin/alertmanager' }
        - { src: 'amtool', dest: '/usr/local/bin/amtool' }

    - name: Copy Alertmanager config
      copy:
        src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager.yml"
        dest: /etc/alertmanager/alertmanager.yml
        owner: prometheus
        group: prometheus
        remote_src: yes

    - name: Configure Alertmanager service
      copy:
        dest: /etc/systemd/system/alertmanager.service
        content: |
          [Unit]
          Description=Prometheus Alertmanager
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/alertmanager \
            --config.file=/etc/alertmanager/alertmanager.yml \
            --storage.path=/var/lib/alertmanager

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Alertmanager
      systemd:
        name: alertmanager
        daemon_reload: yes
        state: started
        enabled: yes

    - name: Install Grafana dependencies
      apt:
        name:
          - software-properties-common
          - apt-transport-https
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Start and enable Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

  post_tasks:
    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/prometheus.tar.gz
        - /tmp/prometheus-{{ prometheus_version }}.linux-amd64
        - /tmp/alertmanager.tar.gz
        - /tmp/alertmanager-{{ alertmanager_version }}.linux-amd64

   