---
- name: Install and configure Node Exporter
  hosts: target
  become: yes
  tasks:
    - name: Download Node Exporter tarball
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
        dest: /tmp/
        mode: '0755'

    - name: Extract Node Exporter tarball
      ansible.builtin.unarchive:
        src: /tmp/node_exporter-1.8.2.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Node Exporter binary
      ansible.builtin.copy:
        src: /tmp/node_exporter-1.8.2.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: yes

    - name: Create systemd service for Node Exporter
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=default.target
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable Node Exporter service
      ansible.builtin.systemd:
        name: node_exporter
        state: started
        enabled: yes